//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminIslem
    {
        public AdminIslem()
        {
            this.TrendSaclar = new HashSet<TrendSaclar>();
        }
    
        public int id { get; set; }
        public string SalonAd { get; set; }
        public string BerberKulAdi { get; set; }
        public string BerberSifre { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual ICollection<TrendSaclar> TrendSaclar { get; set; }
    }
}
