//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BerberSayfa
    {
        public BerberSayfa()
        {
            this.Fiyat = new HashSet<Fiyat>();
            this.Islemler = new HashSet<Islemler>();
            this.Kampanyalar = new HashSet<Kampanyalar>();
            this.MusteriYorumlari = new HashSet<MusteriYorumlari>();
            this.OtomatikMail = new HashSet<OtomatikMail>();
            this.Personel = new HashSet<Personel>();
            this.Randevular = new HashSet<Randevular>();
        }
    
        public int id { get; set; }
        public string SalonAd { get; set; }
        public string KoltukSayisi { get; set; }
        public string SalonAdres { get; set; }
        public string SalonTel { get; set; }
        public string VitrinFoto { get; set; }
        public string VitrinYazi { get; set; }
        public string SalonMail { get; set; }
        public string SalonHakkinda { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SalonID { get; set; }
        public string iLveiLce { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual ICollection<Fiyat> Fiyat { get; set; }
        public virtual ICollection<Islemler> Islemler { get; set; }
        public virtual ICollection<Kampanyalar> Kampanyalar { get; set; }
        public virtual ICollection<MusteriYorumlari> MusteriYorumlari { get; set; }
        public virtual ICollection<OtomatikMail> OtomatikMail { get; set; }
        public virtual ICollection<Personel> Personel { get; set; }
        public virtual ICollection<Randevular> Randevular { get; set; }
    }
}
