//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISLEM
    {
        public int ID { get; set; }
        public int STATUS { get; set; }
        public int SALONID { get; set; }
        public string SALONAD { get; set; }
        public string AD { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual SALON SALON { get; set; }
    }
}
