//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public Islemler()
        {
            this.Fiyat = new HashSet<Fiyat>();
            this.Randevular = new HashSet<Randevular>();
        }
    
        public int id { get; set; }
        public Nullable<int> BerberId { get; set; }
        public string SalonAd { get; set; }
        public string IslemAd { get; set; }
        public Nullable<decimal> IslemFiyat { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Fiyat> Fiyat { get; set; }
        public virtual ICollection<Randevular> Randevular { get; set; }
        public virtual BerberSayfa BerberSayfa { get; set; }
    }
}
