//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public Kullanıcılar()
        {
            this.AdminGiris = new HashSet<AdminGiris>();
            this.AdminIslem = new HashSet<AdminIslem>();
            this.MüsteriKayit = new HashSet<MüsteriKayit>();
            this.BerberSayfa = new HashSet<BerberSayfa>();
        }
    
        public int id { get; set; }
        public Nullable<int> Yetki { get; set; }
        public string isim { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<AdminGiris> AdminGiris { get; set; }
        public virtual ICollection<AdminIslem> AdminIslem { get; set; }
        public virtual ICollection<MüsteriKayit> MüsteriKayit { get; set; }
        public virtual ICollection<BerberSayfa> BerberSayfa { get; set; }
    }
}
