//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BerberimEntities : DbContext
    {
        public BerberimEntities()
            : base("name=BerberimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminGiris> AdminGiris { get; set; }
        public virtual DbSet<AdminIslem> AdminIslem { get; set; }
        public virtual DbSet<Fiyat> Fiyat { get; set; }
        public virtual DbSet<Islemler> Islemler { get; set; }
        public virtual DbSet<Kampanyalar> Kampanyalar { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public virtual DbSet<MusteriYorumlari> MusteriYorumlari { get; set; }
        public virtual DbSet<MüsteriKayit> MüsteriKayit { get; set; }
        public virtual DbSet<OtomatikMail> OtomatikMail { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<TrendSaclar> TrendSaclar { get; set; }
        public virtual DbSet<Randevular> Randevular { get; set; }
        public virtual DbSet<SalonFotolar> SalonFotolar { get; set; }
        public virtual DbSet<KesilenSacModeller> KesilenSacModeller { get; set; }
        public virtual DbSet<BerberSayfa> BerberSayfa { get; set; }
    }
}
