//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        public MUSTERI()
        {
            this.RANDEVU = new HashSet<RANDEVU>();
            this.YORUM = new HashSet<YORUM>();
        }
    
        public int ID { get; set; }
        public int STATUS { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ADRES { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public string DOGUMTARIHI { get; set; }
        public string SIFRE { get; set; }
        public string FOTO { get; set; }
    
        public virtual ICollection<RANDEVU> RANDEVU { get; set; }
        public virtual ICollection<YORUM> YORUM { get; set; }
    }
}
