//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MüsteriKayit
    {
        public MüsteriKayit()
        {
            this.Fiyat = new HashSet<Fiyat>();
            this.MusteriYorumlari = new HashSet<MusteriYorumlari>();
            this.OtomatikMail = new HashSet<OtomatikMail>();
            this.Randevular = new HashSet<Randevular>();
        }
    
        public int id { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriMail { get; set; }
        public string MusteriTel { get; set; }
        public string MusteriDogumTarihi { get; set; }
        public string MusteriKullaniciAdi { get; set; }
        public string MusteriKullaniciSifre { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Fiyat> Fiyat { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual ICollection<MusteriYorumlari> MusteriYorumlari { get; set; }
        public virtual ICollection<OtomatikMail> OtomatikMail { get; set; }
        public virtual ICollection<Randevular> Randevular { get; set; }
    }
}
