//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVU
    {
        public int ID { get; set; }
        public Nullable<int> SALONID { get; set; }
        public Nullable<int> MUSTERIID { get; set; }
        public Nullable<int> ISLEMID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string SALONAD { get; set; }
        public string KOLTUKSAY { get; set; }
        public string SALONTEL { get; set; }
        public string SALONMAIL { get; set; }
        public string PERSONEL { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public string MUSTERITEL { get; set; }
        public string MUSTERIMAIL { get; set; }
        public Nullable<System.DateTime> RANDEVUTARIH { get; set; }
        public string RANDEVUSAAT { get; set; }
    
        public virtual MUSTERI MUSTERI { get; set; }
        public virtual SALON SALON { get; set; }
    }
}
