//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int id { get; set; }
        public Nullable<int> BerberId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> IslemId { get; set; }
        public string SalonAd { get; set; }
        public string KoltukSayisi { get; set; }
        public string SalonTel { get; set; }
        public string SalonMail { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string MüsteriAd { get; set; }
        public string MüsteriTel { get; set; }
        public string MusteriMail { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public Nullable<System.TimeSpan> RandevuSaati { get; set; }
        public string IslemAd { get; set; }
        public Nullable<decimal> IslemFiyat { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Islemler Islemler { get; set; }
        public virtual MüsteriKayit MüsteriKayit { get; set; }
        public virtual BerberSayfa BerberSayfa { get; set; }
    }
}
