//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRENDHAIRS
    {
        public int ID { get; set; }
        public string TRENDADI { get; set; }
        public string FOTO { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
