//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrendSaclar
    {
        public int id { get; set; }
        public string SacModelFoto { get; set; }
        public Nullable<int> TrendID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string yeni { get; set; }
    
        public virtual AdminIslem AdminIslem { get; set; }
    }
}
