//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berberim.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YORUM
    {
        public int ID { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> SALONID { get; set; }
        public Nullable<int> MUSTERIID { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public string YORUM1 { get; set; }
    
        public virtual MUSTERI MUSTERI { get; set; }
        public virtual SALON SALON { get; set; }
    }
}
